B03-Killer/WorkConnect

- src/app/(providers)/(root)/video-channel/[name]/_components/VideoRoom/VideoRoom.tsx
- src/app/(providers)/(root)/video-channel/[name]/_utils/videoChannelDelete.ts
- src/app/(providers)/(root)/video-channel/_constants/contants.ts
- src/app/api/channel-user/route.ts
- src/services/channelUser.ts
> feat: 채팅방 삭제 로직 구현

- src/services/channel.ts
- src/types/supabase.ts
> fix: get_existing_channel_id rpc 이름 변경

- src/app/(providers)/(root)/[workspaceId]/chat/(home)/_components/ChannelItem/ChannelItem.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/_utils/subscribe.ts
- src/app/(providers)/(root)/[workspaceId]/chat/add/_hooks/useCreateChannel.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/add/group-setting/page.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/add/page.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/[name]/_components/VideoRoom/VideoRoom.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/prejoin/_components/PrejoinContent/PreJoinContent.tsx
- src/types/channel.ts
- src/types/supabase.ts
> refactor: 화상채팅 목록, 추가로직 통일

- src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
> fix: 채팅방 버그 수정

- src/components/Modal/Modal.tsx
> Modal 컴포넌트에 z-index값 추가

- src/components/TopBar/TopBar.tsx
- src/components/TopBar/index.ts
- src/icons/index.ts
```
<TopBar
title="채팅"
LeftIcon1={<BackButton />}
LeftIcon2={<BackButton />}
RightIcon1={<BackButton />}
RightIcon2={<BackButton />}
/>
```
```
<TopBar title="채팅1" LeftIcon1={<BackButton />} RightIcon1={<BackButton />} />
```
> feat: TopBar 추가

- src/app/(providers)/(root)/[workspaceId]/chat/[id]/layout.tsx
- src/components/BottomNavigationBar/BottomNavigationBar.tsx
- src/components/TopBar/TopBar.tsx
> feat: bottomNav 페이지 이동

- src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/layout.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/[id]/(resource)/layout.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatFooter/ChatFooter.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/UtilsMenus/UtilsMenus.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/add/(home)/layout.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/add/(home)/page.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/add/_hooks/useCreateChannel.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/add/_provider/SearchUsersProvider.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/layout.tsx
- src/components/ChatCard/ChatCard.tsx
- src/hooks/useWorkspaceUserId.ts
- src/icons/Pin.svg
- src/icons/index.ts
> feat: 채팅 목업 키 제거

- src/app/(providers)/(root)/[workspaceId]/chat/add/group-setting/page.tsx
- src/components/BottomNavigationBar/BottomNavigationBar.tsx
- src/components/NavigationBar/NavigationBar.tsx
- src/icons/index.ts
- src/providers/SnackBarContext.tsx
> fix: 스낵바, bottomNav 오류

- src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/UtilsMenus/UtilsMenus.tsx
> 채팅 UI 상대방 화면 수정, 하드코딩 수정

- src/components/Avatar/Avatar.tsx
- src/components/Avatar/index.ts
- src/icons/index.ts
storybook 문서화는 나중에 해두겠습니다.
```
<Avatar src={image} size="40px" />
```
```
<Avatar size="40px" />
```
```
<Avatar size="40px" variant="square" />
```
> feat: Avatar 시스템 컴포넌트 추가

- src/app/(providers)/(root)/page.tsx
> style: 랜딩 스타일 수정

- src/app/layout.tsx
> feat: 애플 메타데이터 애플리케이션 설정

- src/app/layout.tsx
> style: 아이폰 상태바 테마 변경

- src/app/(providers)/(root)/[workspaceId]/profile/[targetWorkspaceUserId]/page.tsx
- src/hooks/useWorkspaceUser.ts
> fix: 프로필 페이지 변경시 한박자 늦게 변경되는 현상 수정

- package-lock.json
- package.json
- src/app/(providers)/(root)/[workspaceId]/(home)/page.tsx
- src/app/(providers)/(root)/[workspaceId]/_components/HomeMemberCard/HomeMemberCard.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/add/(home)/layout.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/add/group-setting/page.tsx
- src/components/TopSelect/TopSelect.tsx
- src/icons/Check1.svg
- src/icons/index.ts
- tailwind.config.ts
> style: 체크 아이콘 변경

- src/api/chatAPI.ts
- src/app/(providers)/(root)/[workspaceId]/chat/(home)/_components/ChannelItem/ChannelItem.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/(home)/_hooks/useChatHandlers.ts
- src/app/(providers)/(root)/[workspaceId]/chat/[id]/(home)/page.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/Chat/Chat.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatMessages/ChatMessages.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatNotice/ChatNotice.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/add/_components/SearchResults.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/add/_components/SelectedUsers.tsx
- src/components/Avatar/Avatar.tsx
> feat: 공지사항 삭제시에도 리얼타임 반영

- src/app/(providers)/(root)/[workspaceId]/chat/_constants/constants.ts
- src/app/(providers)/(root)/[workspaceId]/chat/_hooks/useQueryChat.tsx
> fix: 채널 목록 쿼리키 미반영 개선

- src/app/(providers)/(root)/[workspaceId]/chat/(home)/page.tsx
> fix: 쿼리키 리얼타임에도 반영

- src/app/(providers)/(root)/workspace/landing/page.tsx
- src/app/(providers)/(root)/workspace/new/page.tsx
- 카카오 워크스페이스 랜딩페이지 접속 오류 해결
- 로그인 후 초대코드 입력 및 새워크스페이스 생성 추가
- 초대코드 중복 입력 시 경고 추가
> 카카오 워크스페이스 랜딩페이지 접속 오류 해결 및 새 워크스페이스 생성 추가

- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/[name]/_components/VideoConference/CustomVideoConference.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/[name]/_components/VideoRoom/VideoRoom.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/_components/DeviceMenu/DeviceMenu.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/_components/MediaDeviceMenu/MediaDeviceMenu.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/_components/MediaDeviceMenu/index.ts
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/_components/MediaDeviceMenuButton/MediaDeviceMenuButton.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/_components/MediaDeviceMenuButton/index.ts
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/_components/ToggleIcon/getSourceIcon.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/_components/TrackToggle/TrackToggle.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/_components/VideoChannel/VideoChannel.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/_components/VideoChannel/index.ts
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/prejoin/_components/CustomPrejoin/CustomPrejoin.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/prejoin/_components/PrejoinContent/PreJoinContent.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/prejoin/_components/PrejoinHeader/PrejoinHeader.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/prejoin/page.tsx
코드 리팩토링을 했지만,, 오류 해결하는 과정에서 살짝 지저분해 져서 다시 손 봐야 할 것 같아요...  최적화도 해보고 안되면 우선 넘기겠습니다..
> 영상통화방 입장 불가했던 원인 해결

- package-lock.json
- package.json
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/[name]/_components/VideoRoom/VideoRoom.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/prejoin/_components/CustomPrejoin/CustomPrejoin.tsx
- src/app/(providers)/(root)/[workspaceId]/video-channel/(main)/prejoin/_components/PrejoinContent/PreJoinContent.tsx
Reverts B03-Killer/WorkConnect#212
> Revert "fix:영상진입 에러 해결2"

- src/components/BottomNavigationBar/BottomNavigationBar.tsx
Reverts B03-Killer/WorkConnect#220
> Revert "feat: bottom nav 마이페이지 메뉴 삭제"

- src/components/BottomNavigationBar/BottomNavigationBar.tsx
> feat: 하단바 마이페이지 메뉴 제거

- src/components/SelectHeader/SelectHeader.tsx
- src/components/TopSelect/TopSelect.tsx
- home화면에서 다른 워크스페이스 로그인 클릭시 -> workspace/landing 이동
- 초대코드 입력, 새 워크스페이스 생성 시 home으로 이동
> 다른 워크스페이스 로그인 플로우 추가

- src/components/EditTextfield/EditTextfield.stories.tsx
- src/components/EditTextfield/EditTextfield.tsx
- src/components/EditTextfield/index.ts
readOnly 속성을 추가한 
EditTextfield 컴포넌트를 새로 제작하였습니다.
연필 아이콘 클릭 시 글작성이 가능합니다.
> EditTextfield 컴포넌트 추가

- src/hooks/useWorkspaceUserList.ts
Reverts B03-Killer/WorkConnect#232
> Revert "워크스페이스 생성시 멤버목록 보이는 오류 수정" 

- src/app/(providers)/(root)/[workspaceId]/chat/[id]/_components/ChatDetailLayout/ChatDetailLayout.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/[id]/_hook/useGetChannelName.tsx
- src/app/(providers)/(root)/[workspaceId]/chat/_utils/getChannelName.ts
- src/app/(providers)/(root)/[workspaceId]/chat/add/_hooks/useCreateChannel.tsx
> fix: 리팩터링 후 채널명이 보이지 않는 현상 수정

- src/app/api/channel-user/route.ts
- src/app/api/channel/[id]/users/constants.ts
- src/app/api/channel/[id]/users/route.ts
- src/app/api/channel/existing-id/constants.ts
- src/app/api/channel/existing-id/route.ts
- src/app/api/chat/(home)/constants.ts
- src/app/api/chat/(home)/route.ts
- src/app/api/chat/[id]/constants.ts
- src/app/api/chat/[id]/latest-notice/constants.ts
- src/app/api/chat/[id]/latest-notice/route.ts
- src/app/api/chat/[id]/route.ts
- src/app/api/workspace/[id]/users/search/constants.ts
- src/app/api/workspace/[id]/users/search/route.ts
- src/services/chat.ts
> api 응답 status 설정

- src/components/PageLayout/PageLayout.tsx
> pc 일때 하단바 영역 제거

- src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/ChatDetailLayout/ChatDetailLayout.tsx
> style: 모바일 헤더 스타일 수정

- src/app/(providers)/(root)/[workspaceId]/(home)/layout.tsx
- src/app/(providers)/(root)/[workspaceId]/profile/[targetWorkspaceUserId]/layout.tsx
- src/app/(providers)/(root)/[workspaceId]/to-do-list/(home)/layout.tsx
- src/app/(providers)/(root)/[workspaceId]/to-do-list/_components/DateSelect/DateSelect.tsx
- src/app/(providers)/(root)/[workspaceId]/to-do-list/_components/DateSelect/index.ts
- src/app/(providers)/(root)/[workspaceId]/to-do-list/_components/PcHeader/PcHeader.tsx
- src/app/(providers)/(root)/[workspaceId]/to-do-list/_components/Todo/Todo.tsx
- src/app/(providers)/(root)/[workspaceId]/to-do-list/_components/TodoListMain/TodoListMain.tsx
- src/app/(providers)/(root)/[workspaceId]/to-do-list/add/[id]/_components/Header/Header.tsx
- src/app/(providers)/(root)/[workspaceId]/to-do-list/add/[id]/layout.tsx
- src/components/Layout/PageLayout/PageLayout.tsx
- src/components/Layout/SelectHeader/SelectHeader.tsx
> 헤더 및 사이드바 레이아웃 수정

- src/app/(providers)/(root)/[workspaceId]/channels/(chat)/_hook/useChatQuery.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/(chat)/_utils/getQueryOptions.ts
- src/app/(providers)/(root)/[workspaceId]/channels/_utils/getQueryOptions.ts
- src/providers/QueryProvider.tsx
> fix: 채팅 메세지에 stale time이 있어서 데이터가 바로 반영되지 않는 현상 수정

- src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/Chats/Components.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelItem/ChannelItem.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/ChannelList.tsx
- src/components/ChatCard/ChatCard.tsx
- src/types/channel.ts
- src/types/supabase.ts
> 안 읽은 채팅 목록에서 보여지기 (realtime 미적용)

- src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/ChatDetailLayout/ChatDetailLayout.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelItem/ChannelItem.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/ChannelList.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/_hooks/useChannelHandlers.ts
- src/app/(providers)/(root)/[workspaceId]/profile/[targetWorkspaceUserId]/_components/EditOrMessageButton/EditOrMessageButton.tsx
- src/components/Layout/PageLayout/PageLayout.tsx
- src/services/channel.ts
- src/types/channel.ts
- src/types/supabase.ts
> 공지방 노출시 채널 목록에 노출되도록 개선

- src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/ChatNotice/ChatNotice.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_components/Messages/Messages.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_hooks/useChatHandlers.ts
- src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/_utils/subscribe.ts
- src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/ChannelList.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/_hooks/useChannelHandlers.ts
- src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/_utils/subscribe.ts
- src/utils/createRealtimeChannel.ts
> realtime cleanup 미작동 오류 수정 / 채팅 수신시 채널 활동시간 업데이트

- src/app/(providers)/(root)/auth/signup/page.tsx
- src/app/(providers)/(root)/page.tsx
- src/app/(providers)/(root)/password-find/page.tsx
- src/app/(providers)/(root)/workspace/landing/_hooks/useInvite.ts
- src/app/(providers)/(root)/workspace/landing/page.tsx
- src/app/(providers)/(root)/workspace/new/_hooks/useNewWorkspace.ts
- src/app/(providers)/(root)/workspace/new/page.tsx
- src/app/api/workspace-list/route.ts
워크스페이스 생성 및 초대코드 입력 시 채팅에 "전체_공지방" 추가
close #304
> 워크스페이스 생성시 "전체_공지방" 추가

- src/app/(providers)/(root)/[workspaceId]/channels/add/(home)/page.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/add/_components/AddChannelLayout/AddChannelLayout.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/add/_components/SearchMemberCard/SearchMemberCard.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/add/_components/SelectedUsers/SelectedUsers.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/add/group-setting/_components/GroupNameInput/GroupNameInput.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/add/group-setting/page.tsx
> style: 채팅 추가 검색 페이지 pc 스타일 반영

- src/assets/userStatusList.ts
> 상태메세지 아이콘 추가

- src/app/(providers)/(root)/[workspaceId]/channels/(home)/layout.tsx
- src/components/Layout/PageLayout/PageLayout.tsx
- src/components/Layout/SelectHeader/SelectHeader.tsx
- src/components/Layout/TopBar/TopBar.tsx
> channel pc 디자인 변경 / 채팅 mobile 헤더 변경

- src/app/(providers)/(root)/auth/signup/page.tsx
- src/app/(providers)/(root)/page.tsx
- src/app/(providers)/(root)/workspace/landing/_hooks/useInvite.ts
- src/app/(providers)/(root)/workspace/landing/page.tsx
- src/app/(providers)/(root)/workspace/new/page.tsx
> 초대코드 페이지 로직 오류 수정 및 모바일ui 수정

- src/app/(providers)/(root)/[workspaceId]/channels/(chat)/[id]/(home)/loading.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/(home)/loading.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/_components/ChannelList/ChannelList.tsx
- src/app/(providers)/(root)/[workspaceId]/channels/_components/TopBarButtons/TopBarButtons.tsx
- src/app/loading.tsx
- src/hooks/useWorkspaceId.ts
> feat: 채팅 로딩 추가

- .github/workflows/deploy.yml
- .gitignore
- build.sh
> github actions 개인 레포를 연결하여 배포 자동화 추가

- build.sh
> 빌드스크립트 수정 (스토리북 추가)

- README.md
> docs: 스토리북 배포 URL 변경

- src/api/channelAPI.ts
- src/app/api/channel/[id]/update-active-at/route.ts
> updateChannelActiveAt post -> put으로 변경

- .github/workflows/supabase-activity-scheduler.yml
> fix: workflow checkout 코드 추가
